insert into tb_funcionario (cod, cargo, data_admissao) values (1, 'audio', '01/08/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (2, 'audio', '15/01/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (3, 'audio', '27/11/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (4, 'audio', '02/11/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (5, 'video', '07/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (6, ''video', '01/06/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (7, 'video', '24/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (8, ''video', '08/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (9, ''video', '28/08/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (10, 'culinaria', '26/01/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (11, 'culinaria', '26/02/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (12, 'culinaria', '09/01/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (13, 'culinaria', '12/12/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (14, 'servicosgerais', '05/02/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (15, 'servicosgerais', '20/08/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (16, 'servicosgerais', '10/08/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (17, 'servicosgerais', '11/08/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (18, 'servicosgerais', '22/02/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (19, 'servicosgerais', '20/05/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (20, 'servicosgerais', '29/12/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (21, 'Systems Administrator IV', '12/03/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (22, 'Research Assistant I', '27/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (23, 'Dental Hygienist', '10/06/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (24, 'Teacher', '28/06/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (25, 'Accountant II', '02/06/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (26, 'Physical Therapy Assistant', '18/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (27, 'Payment Adjustment Coordinator', '22/06/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (28, 'Help Desk Technician', '15/03/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (29, 'Legal Assistant', '12/02/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (30, 'Geological Engineer', '23/10/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (31, 'Senior Quality Engineer', '30/10/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (32, 'Staff Accountant IV', '28/04/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (33, 'Structural Engineer', '06/05/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (34, 'Teacher', '20/01/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (35, 'Recruiting Manager', '29/12/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (36, 'Technical Writer', '30/05/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (37, 'Compensation Analyst', '27/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (38, 'Social Worker', '05/09/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (39, 'Accounting Assistant III', '20/03/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (40, 'Account Coordinator', '06/01/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (41, 'Chief Design Engineer', '17/04/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (42, 'Financial Advisor', '17/10/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (43, 'Structural Analysis Engineer', '15/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (44, 'Clinical Specialist', '06/05/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (45, 'Executive Secretary', '31/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (46, 'Statistician IV', '11/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (47, 'VP Marketing', '10/09/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (48, 'Operator', '08/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (49, 'Dental Hygienist', '16/11/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (50, 'Sales Representative', '20/02/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (51, 'Senior Sales Associate', '04/08/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (52, 'Chemical Engineer', '17/08/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (53, 'Civil Engineer', '26/03/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (54, 'Marketing Manager', '26/06/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (55, 'Food Chemist', '03/03/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (56, 'Quality Engineer', '11/10/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (57, 'Environmental Tech', '08/08/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (58, 'Web Developer II', '19/03/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (59, 'Pharmacist', '29/01/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (60, 'Technical Writer', '03/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (61, 'Environmental Tech', '13/01/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (62, 'Help Desk Operator', '08/12/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (63, 'Analyst Programmer', '10/04/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (64, 'Automation Specialist I', '11/01/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (65, 'Tax Accountant', '26/04/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (66, 'Software Consultant', '29/09/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (67, 'Staff Accountant I', '12/03/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (68, 'Librarian', '01/06/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (69, 'Senior Developer', '14/12/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (70, 'Accounting Assistant I', '16/10/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (71, 'Programmer II', '11/02/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (72, 'Information Systems Manager', '15/11/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (73, 'Community Outreach Specialist', '14/09/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (74, 'Structural Engineer', '06/05/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (75, 'Media Manager I', '04/02/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (76, 'Account Representative IV', '28/10/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (77, 'Legal Assistant', '30/09/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (78, 'Recruiter', '08/12/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (79, 'VP Product Management', '15/06/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (80, 'Research Nurse', '02/11/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (81, 'Senior Editor', '25/12/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (82, 'Help Desk Technician', '28/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (83, 'Sales Representative', '02/11/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (84, 'Software Engineer III', '04/11/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (85, 'Clinical Specialist', '10/09/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (86, 'Assistant Media Planner', '31/10/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (87, 'Senior Developer', '13/09/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (88, 'Account Coordinator', '09/04/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (89, 'Sales Associate', '07/11/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (90, 'Media Manager I', '16/12/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (91, 'General Manager', '06/12/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (92, 'Information Systems Manager', '21/06/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (93, 'Financial Analyst', '30/07/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (94, 'VP Accounting', '19/02/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (95, 'Financial Advisor', '03/12/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (96, 'Nurse', '06/05/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (97, 'Nurse', '13/05/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (98, 'Developer III', '22/11/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (99, 'Programmer Analyst IV', '15/12/2022');
insert into tb_funcionario (cod, cargo, data_admissao) values (100, 'Nuclear Power Engineer', '11/04/2022');
